spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bankfirst
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
bank:
  title: First bank
  country: RU
server:
  port: 8081
